var app=angular.module("app",["ngSanitize","angular-cache"]);app.filter("genVideoTag",["$sce",function(e){return function(d){if(d)return e.trustAsHtml(d)}}]);app.filter("activityTime",function(){return function(e){if(""!==e&&e){var d=new Date(1970,0,1);d.setMinutes(1*e.toString().match(/\d+/)[0]);return moment(d).format("mm")}return e}});
function catalougePreviewCtrl(e,d,g,f,c,a){var b=this;b.activityTypeId=0;b.isDoneQuiz=!1;b.getActivityTemplate=function(b){var a="";switch(b){case 1:a="/views/preview/activity_QA.html";break;case 2:a="/views/preview/activity_text.html";break;case 3:a="/views/preview/activity_video.html";break;case 4:a="/views/preview/activity_quiz.html"}return a};b.getQuizAnswerTemplate=function(b,a){var c="";switch(b){case 1:case 4:c="/views/preview/quiz_multi.html?v\x3d"+a;break;case 3:c="/views/preview/quiz_single.html?v\x3d"+
a;break;case 5:c="/views/preview/quiz_text.html?v\x3d"+a}return c};b.finishLoadingQuizAnswer=function(){c(function(){componentHandler.upgradeElements(document.querySelector("#dActivityInfo"))},1)};b.computeActivityTimeClass=function(a,c,d,e){var f="",g=0;angular.forEach(b.listActivity,function(a,c){a.activityId==b.activityId&&(g=c)});f=c?"bg_first":d?"bg_last":"bg_middle";e.activityId==b.activityId?f+=" active":e.activityId==b.lastDoneActivityId?f+=" last-active":a<g&&(f+=" past");return f};var k=
function(a){var c=g.defer();f.getActivityDetails(a).then(function(a){b.activityDetails=a.data;c.resolve()});return c.promise},l=function(a,c){var d=g.defer();f.getActivityCatalouge({unitId:a,lessonId:c}).then(function(a){b.listActivity=a.data;d.resolve()});return d.promise};e.init=function(a,c,d){g.all([k(d),l(a,c)]).then(function(){b.activityTypeId=b.activityDetails.activityTypeId;b.activityId=d;4==b.activityTypeId&&f.getQuizQuestion(b.activityId).then(function(a){b.listQuestion=a.data;b.listQuestion&&
0<b.listQuestion.length&&(b.currentQuizQuestion=b.listQuestion[0],b.currentQuizIndex=0)})})};b.computeQuestionPagingClass=function(a,c){var d="";c.questionId==b.currentQuizQuestion.questionId?d="active":c.isTraineeAnswerRight?d="past ok":void 0==c.isTraineeAnswerRight||c.isTraineeAnswerRight||(d="past error");return d};b.isShowPaging=function(a){return 0==b.currentQuizIndex&&a<=b.currentQuizIndex+2||1==b.currentQuizIndex&&1==b.currentQuizIndex%2&&a<=b.currentQuizIndex+1&&a>=b.currentQuizIndex-1||
1<b.currentQuizIndex&&a<=b.currentQuizIndex&&a>=b.currentQuizIndex-2||b.currentQuizIndex+1==b.listQuestion.length-1&&a>=b.currentQuizIndex-3||b.currentQuizIndex==b.listQuestion.length-1&&a>=b.currentQuizIndex-4||a==b.listQuestion.length-1};b.isHidePaging=function(a){return!b.isShowPaging(a)&&5<b.listQuestion.length&&a+1==b.listQuestion.length-1};b.nextQuizQuestion=function(){b.traineeAnswerErrorText="";var a=0<Enumerable.From(b.currentQuizQuestion.listAnswer).Count(function(a){return a.isChecked}),
c=Enumerable.From(b.currentQuizQuestion.listAnswer).Where(function(a){return a.isChecked}).ToArray(),d=b.currentQuizQuestion.questionTypeId;if(1!=d&&4!=d||a)if(3!=d||b.currentQuizQuestion.traineeAnswer)if(5!=d||b.currentQuizQuestion.traineeAnswer)if(5==d&&2E3<b.currentQuizQuestion.traineeAnswer.length)b.traineeAnswerErrorText="Sorry, your answer is too long (max: 2000 characters)";else{var a=b.currentQuizQuestion.rightAnswerIndex,e=!1;if(1==d||4==d){var f=!0,g=a.split(","),h="";angular.forEach(c,
function(a){h+=(""!=h?",":"")+a.answerIndex.toString();-1==g.indexOf(a.answerIndex.toString())&&(f=!1)});f&&(f=c.length==g.length);Enumerable.From(b.listQuestion).First(function(a){return a.questionId==b.currentQuizQuestion.questionId}).isTraineeAnswerRight=f;Enumerable.From(b.listQuestion).First(function(a){return a.questionId==b.currentQuizQuestion.questionId}).traineeAnswer=h;e=f}else 3==d?(e=b.currentQuizQuestion.traineeAnswer==a,Enumerable.From(b.listQuestion).First(function(a){return a.questionId==
b.currentQuizQuestion.questionId}).isTraineeAnswerRight=e):5==d&&(Enumerable.From(b.listQuestion).First(function(a){return a.questionId==b.currentQuizQuestion.questionId}).isTraineeAnswerRight=!0);!b.isRedoingQiz&&b.currentQuizIndex+1<=b.listQuestion.length-1?(b.answerLoaded=!1,b.isLastQuizQuestion=b.currentQuizIndex+1==b.listQuestion.length-1,b.currentQuizIndex+=1,b.currentQuizQuestion=b.listQuestion[b.currentQuizIndex]):b.isRedoingQiz&&!e?b.traineeAnswerErrorText="Sorry, this is not correct":b.isRedoingQiz&&
e&&b.currentErrorQuizIndex+1<=b.errorQuestion.length-1?(b.currentErrorQuizIndex+=1,b.currentQuizQuestion=b.errorQuestion[b.currentErrorQuizIndex],b.currentQuizIndex=b.listQuestion.indexOf(b.currentQuizQuestion),b.currentQuizType=3==b.currentQuizQuestion.questionTypeId?"radio":"checkbox",b.isLastQuizQuestion=b.currentQuizIndex==b.listQuestion.length-1):(b.currentQuizIndex=b.listQuestion.length-1,c=0<Enumerable.From(b.listQuestion).Count(function(a){return!a.isTraineeAnswerRight}),b.isRedoingQiz||Enumerable.From(b.listQuestion).Select("x \x3d\x3e { questionId: x['questionId'], traineeAnswer: x['traineeAnswer'].toString() , isTraineeAnswerRight: x['isTraineeAnswerRight'] }").ToArray(),
b.isDoneQuiz=!0,b.hasErrorQuiz=c)}else b.traineeAnswerErrorText="Please provide an answer";else b.traineeAnswerErrorText="Please choose an answer";else b.traineeAnswerErrorText="Please choose an answer"};b.redoQuiz=function(){b.isRedoingQiz=!0;b.isDoneQuiz=!1;b.errorQuestion=Enumerable.From(b.listQuestion).Where(function(a){return!a.isTraineeAnswerRight}).ToArray();b.currentErrorQuizIndex=0;b.currentQuizQuestion=b.errorQuestion[0];b.currentQuizIndex=b.listQuestion.indexOf(b.currentQuizQuestion);b.currentQuizType=
3==b.currentQuizQuestion.questionTypeId?"radio":"checkbox";b.isLastQuizQuestion=b.currentQuizIndex==b.listQuestion.length-1};b.processingActivityData=function(b){b=b.replace(/href/g,'target\x3d"_blank" href');return a.trustAsHtml(b)};b.genVideoTag=function(b){return a.trustAsHtml(b)}}catalougePreviewCtrl.$inject="$scope $rootScope $q dataService $timeout $sce".split(" ");app.controller("catalougePreviewCtrl",catalougePreviewCtrl);
app.factory("sessionService",["$rootScope",function(e){var d,g=[];return{getUserSession:function(){return d},setUserSession:function(f){d=f;e.$broadcast("updateSession")},pushUserMenu:function(d){g.push(d)},getUserMenu:function(){return g},clearUserSession:function(){d=void 0;e.$broadcast("updateSession")},isLogin:function(){return d?!0:!1},isAdmin:function(){return d&&1==d.userTypeId?!0:!1}}}]);
app.factory("dataService",["$http","CacheFactory","$timeout",function(e,d,g){var f=function(a){return e.post(a).then(function(a){return a.data})},c=function(a,b){return e.post(a,b).then(function(a){return a.data})};d.get("masterDataCache")||d.createCache("masterDataCache",{deleteOnExpire:"aggressive",recycleFreq:6E4});d.get("masterDataCache");return{getModules:function(a){return c("/api/getModules",a)},doLogin:function(a){return c("/api/doLogin",a)},doLogout:function(){return f("/api/doLogout")},
getUserSession:function(){return f("/api/getUserSession")},getStudentList:function(a){return c("/api/getStudentList",a)},getAllCenter:function(){return e.get("/api/getAllCenter").then(function(a){return a.data})},getAllCourse:function(){return e.get("/api/getAllCourse").then(function(a){return a.data})},getIntroClassByCenterAndCourse:function(a){return c("/api/getIntroClassByCenterAndCourse",a)},getIncomingFirstClass:function(a){return c("/api/getIncomingFirstClass",a)},addNewStudent:function(a){return c("/api/addNewStudent",
a)},getPendingCheckAttendanceClass:function(a){return c("/api/getPendingCheckAttendanceClass",a)},getIncomingClass:function(a){return c("/api/getIncomingClass",a)},getClassSchedule:function(a){return c("/api/getClassSchedule",a)},getClassInfoById:function(a){return c("/api/getClassInfoById",a)},getStudentByClass:function(a){return c("/api/getStudentByClass",a)},changeClassTrainer:function(a){return c("/api/changeClassTrainer",a)},changeClassTime:function(a){return c("/api/changeClassTime",a)},updateStudentAttendance:function(a){return c("/api/updateStudentAttendance",
a)},updateClassAttendanceCheck:function(a){return c("/api/updateClassAttendanceCheck",a)},getAllTrainer:function(){return e.get("/api/getAllTrainer").then(function(a){return a.data})},getStudentInfo:function(a){return c("/api/getStudentInfo",a)},getStudentClasses:function(a){return c("/api/getStudentClasses",a)},getStudentActivityLog:function(a){return c("/api/getStudentActivityLog",a)},getAllCommentType:function(){return f("/api/getAllCommentType")},getAllCommentResult:function(a){return c("/api/getAllCommentResult",
a)},resetStudentPassword:function(a){return c("/api/resetStudentPassword",a)},addActivityLog:function(a){return c("/api/addActivityLog",a)},getQuizReport:function(a){return c("/api/getQuizReport",a)},getQuizReportDetail:function(a){return c("/api/getQuizReportDetail",a)},getSystemUser:function(a){return c("/api/getSystemUser",a)},getUserType:function(){return e.get("/api/getUserType").then(function(a){return a.data})},addNewUser:function(a){return c("/api/addNewUser",a)},getStudentProperty:function(a){return c("/api/getStudentProperty",
a)},getStudentQuiz:function(a){return c("/api/getStudentQuiz",a)},getStudentOtherActivity:function(a){return c("/api/getStudentOtherActivity",a)},getCourseActivity:function(a){return c("/api/getCourseActivity",a)},getStudentAllCourse:function(a){return c("/api/getStudentAllCourse",a)},updateStudentCourseStatus:function(a){return c("/api/updateStudentCourseStatus",a)},getOfflineClassForRetake:function(a){return c("/api/getOfflineClassForRetake",a)},retakeStudentClass:function(a){return c("/api/retakeStudentClass",
a)},getUnitInCourse:function(a){return c("/api/getUnitInCourse",a)},getCourseHoliday:function(a){return c("/api/getCourseHoliday",a)},addNewGroupClass:function(a){return c("/api/addNewGroupClass",a)},getLessonInUnit:function(a){return c("/api/getLessonInUnit",a)},getActivityCatalouge:function(a){return c("/api/getActivityCatalouge",a)},getActivityDetails:function(a){return c("/api/getActivityDetails",a)},getQuizQuestion:function(a){return c("/api/getQuizQuestion",a)},getAllGroupClass:function(a){return c("/api/getAllGroupClass",
a)},getAllClassType:function(){return e.get("/api/getAllClassType").then(function(a){return a.data})},getUnitByCourseAndClassType:function(a){return c("/api/getUnitByCourseAndClassType",a)},extendGroupClass:function(a){return c("/api/extendGroupClass",a)}}}]);
app.service("notifyService",function(){this.error=function(d,g){e(d,"error",g)};this.success=function(d,g){e(d,"success",g)};var e=function(d,e,f){new PNotify({text:d,delay:void 0==f?1400:f,icon:!1,styling:"bootstrap3",type:e,width:"290px",animate:{animate:!1},buttons:{sticker:!1,closer:!1}})}});
app.service("progressService",["ngProgressFactory",function(e){var d=e.createInstance();d.setColor("#70ca63");this.start=function(){d.start()};this.complete=function(){d.complete()};this.status=function(){return d.status()};this.reset=function(){d.reset()}}]);